import Image from "next/image";
import Head from "next/head";
//
import Sidebar from "@/components/sidebar";
import Menu from "@/components/menu";
import ScrollButton from "@/components/ScrollButton";
//
import Landing from "./landing";
import AboutMe from "./about";
import Projects from "./projects";
import LatestWork from "./latestWork";
import React from "react";
import { useState } from "react";
import Link from "next/link";

import styles from "@/styles/Home.module.css";

export default function Home() {
  const [currentSection, setCurrentSection] = useState("home");
  const [currentMedia, setCurrentMedia] = useState("desktop");
  const [darkmode, setDarkmode] = useState(false);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main}`}>
        <ScrollButton />
        {/* <div class="scroll-indicator">
          <div class="dots">
            <svg
              data-name="Layer 1"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 8.79 123.3"
              preserveAspectRatio="xMidYMid"
            >
              <circle
                class="dot-7"
                cx="4.39"
                cy="118.91"
                r="4.39"
                fill="#d1d3d4"
              />
              <circle
                class="dot-6"
                cx="4.39"
                cy="99.82"
                r="4.39"
                fill="#d1d3d4"
              />
              <circle
                class="dot-5"
                cx="4.39"
                cy="80.73"
                r="4.39"
                fill="#d1d3d4"
              />
              <circle
                class="dot-4"
                cx="4.39"
                cy="61.64"
                r="4.39"
                fill="#d1d3d4"
              />
              <circle
                class="dot-3"
                cx="4.39"
                cy="42.56"
                r="4.39"
                fill="#d1d3d4"
              />
              <circle
                class="dot-2"
                cx="4.39"
                cy="23.48"
                r="4.39"
                fill="#d1d3d4"
              />
              <circle
                class="dot-1"
                cx="4.39"
                cy="4.39"
                r="4.39"
                fill="#d1d3d4"
              />
            </svg>
          </div>
        </div> */}
        {/* <div class="navbar">
        <div class="links">
          <div class="link home">Home</div>
          <div class="link about-me">About Me</div>
          <div class="link process">My Process</div>
          <div class="link portfolio">Portfolio</div>
          <div class="link latest-work">Latest Work</div>
        </div>
        <div class="link-underscore"></div>
        <div class="hamburger-menu"></div>
      </div> */}
        <div className="navbar">
          <Menu
            currentSection={currentSection}
            setCurrentSection={setCurrentSection}
            currentMedia={currentMedia}
          />
        </div>
        <Sidebar />
        {/* <BrowserRouter>
          <Routes>
            <Route path="/projets" element={null} />
          </Routes>
        </BrowserRouter> */}
      </main>
    </>
  );
}
